pretrained_model_name_or_path: black-forest-labs/FLUX.1-dev
data_config:
  train_batch_size: 1
  num_workers: 4
  img_size: 1024
  caption_dropout_rate: 0
  img_dir: ./test_dataset
  random_ratio: false # support multi crop preprocessing
  caption_type: txt
report_to: null
train_batch_size: 1
output_dir: ./test_lora_saves
max_train_steps: 100
learning_rate: 5e-4
lr_scheduler: constant
lr_warmup_steps: 10
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 0.01
adam_epsilon: 1e-8
max_grad_norm: 1.0
logging_dir: logs
mixed_precision: "no" # should be no for MPS
checkpointing_steps: 25
checkpoints_total_limit: 10
tracker_project_name: lora_test
resume_from_checkpoint: latest
gradient_accumulation_steps: 8
rank: 16
double_blocks: null
disable_sampling: true
sample_every: 250 # sample every this many steps
sample_width: 1024
sample_height: 1024
sample_steps: 20
